app = "your-app-name"  # Replace with the app name from `fly launch`

[build]

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]
